### ISSUE TITLE
Video FlightGear

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#15]
There is a Video Downlink widget in QGC.  I would like a variation of this which grabs screenshots from flightgear when fg is visualizing for us.  If you start flightgear with the --http=8080 option, there is a screenshot available at localhost:8080/screenshot.  I feel it should be fairly straightforward to load this into a widget. 

HUD is a bit trickier, as we'll need to control the camera angle to look "forward".  I'll investigate if that's easy.

**Comment by BojanKverh** [comment]
This is now done with the latest commit. FlightGear Live Video widget is available under Advanced/Tool Widgets
