### ISSUE TITLE
Add separate digital field in the vehicle widget gauges

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#18]
We want to be able to monitor rpm as well as temperature for these, so we want to add a separate digital readout in the center lower portion of the gauge (where there is no arc)

**Comment by BojanKverh** [comment]
Done with the latest commit

**Comment by dcmcshan** [comment]
Let's make the font a bit larger, white, and give it a transparent background.  I think we only need 6 digits, so it can be a bit larger.

**Comment by BojanKverh** [comment]
OK, done.
