### ISSUE TITLE
Have Vehicle Widget better fill it's space

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#21]
There seems to be quite a bit of margin around the graphic.  Scale it to better fill the widget.

**Comment by BojanKverh** [comment]
I think this should be better with the latest commit

**Comment by dcmcshan** [comment]
Better scaled, but now the background is bright cyan!

**Comment by BojanKverh** [comment]
Oh, I put it there only to give me the idea of widget size and I forgot to remove it afterwards. Sorry about that, I removed it in the latest commit.
