### ISSUE TITLE
Change waypoint icon for payloads

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#22]
So, you probably can't see this until you get the waypointmanager, but the map view should show the mission route - from waypoint to waypoint. We need to change the default waypoint icon for navigation waypoint to something that indicated payload waypoint.  Will need to be different color and different shape.  Maybe a red "upside down" teardrop?

**Comment by BojanKverh** [comment]
Teardrop is now used as the waypoint icon

**Comment by dcmcshan** [comment]
I haven't looked yet, but to confirm... Should just be for the payload type of waypoint to distinguish it.-

**Comment by BojanKverh** [comment]
I see. So those "PAY: Deploy 1", "PAY: Deploy 2" and "PAY: Deploy 3" should actually be waypoint types and should be added to the drop down box, where there are already options "NAV: Takeoff", "NAV: Loiter unlim.", etc, for user to choose?

**Comment by dcmcshan** [comment]
Correct!

**Comment by BojanKverh** [comment]
OK, sorry that it took me so long to understand that.

**Comment by dcmcshan** [comment]
My fault for not better specifying.  I'll try to do better in future.

**Comment by BojanKverh** [comment]
It's ok, I hope this time I am closer to getting it right. :)
