### ISSUE TITLE
Replace splash and weight graphic with branding

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#23]
I added a rt/ folder under DroneWidgets.  It has two images.  One is a long splash to replace the QGroundControl default.  The other is just the logo icon to replace the icon in the weight widget.

**Comment by BojanKverh** [comment]
There doesn't seem to be rt/ folder on DroneWidgets or qgroundcontrol.

**Comment by dcmcshan** [comment]
Hm... maybe I didn't commit.  One sec

**Comment by dcmcshan** [comment]
Was held up by a large file violtion in a previous commit.  So, I have just added to qgroundcontrol repo.

**Comment by BojanKverh** [comment]
Now it's ok, thanks.

**Comment by BojanKverh** [comment]
Done with the latest commit.
