### ISSUE TITLE
images/marker1.png

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#25]
Guessing a missing file needed to be uploaded.

RCC: Error in '../qgroundcontrol/libs/opmapcontrol/src/mapwidget/mapresources.qrc': Cannot find file 'images/marker1.png' make[1]: **\* [build-debug/rcc/qrc_mapresources.cpp] Error 1

**Comment by BojanKverh** [comment]
Yes, sorry about that. I uploaded it now.
