### ISSUE TITLE
Additional Widgets

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#8]
Go ahead and widgetize the other gauges we have: Fuel, Weight, and the QFI widgets.  Also Mission Planner - it will end up on a different screen

**Comment by BojanKverh** [comment]
OK. I actually meant to ask if any of these gauges would be used in the VehicleWidget instead of the Temperature ones.

**Comment by dcmcshan** [comment]
Ah.  Probably not.

What we are going to want to do in the future is make the VehicleWidget gauges customizable - so you can select Temperature, Current, RPM, etc.  and the limits and such will change as well.   For now, it’s good.

**Comment by BojanKverh** [comment]
OK. And by widgetize you mean integrate them into qgroundcontrol so that they can be selected from Tool widgets, right?

**Comment by dcmcshan** [comment]
Exactly.

**Comment by BojanKverh** [comment]
OK. Integrated Mission planning widget

**Comment by BojanKverh** [comment]
Integrated fuel, weight and airspeed gauges.

**Comment by BojanKverh** [comment]
Integrated vertical speed and altitude indicators

**Comment by BojanKverh** [comment]
Integrated heading indicator
