### ISSUE TITLE
QcPixmapItem not found

### ISSUE THREAD

**Issue by dcmcshan** [Syzygyx/DroneWidgets#9]
I updated repo and rebuild, and get this error.  Maybe something you did not check in?

Should have more work for you next week!

/Users/dcmcshan/BRYXco/qgroundcontrol/src/ui/flightindicators/WeightGauge.cpp:1: error: 'QcPixmapItem.h' file not found
# include "QcPixmapItem.h"

```
     ^
```

**Comment by BojanKverh** [comment]
Hi Dan,

looks like just a path mismatch. I updated this file and it should compile ok. Strangely enough, it compiled ok on my laptop even before this.
I hope it will work now.
